services:
  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: on-failure
  nginx:
    container_name: nginx
    env_file:
      - .env
    build: ./requirements/nginx
    networks:
      - inception
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    env_file:
      - .env
    build: ./requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
    restart: on-failure

volumes:
 wordpress:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/egomez/data/wordpress'

 mariadb:
  driver: local
  driver_opts:
   type: 'none'
   o: 'bind'
   device: '/home/egomez/data/mariadb'

networks:
 inception:
  driver: bridge